CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE role (
    id BIGINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    status TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE device (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(255),
    longitude DECIMAL(10,6),
    latitude DECIMAL(10,6),
    status TINYINT NOT NULL DEFAULT 1,
    description VARCHAR(255)
);

CREATE TABLE user (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    realName VARCHAR(50) NOT NULL,
    gender VARCHAR(10),
    phone VARCHAR(20),
    deptId BIGINT NOT NULL,
    roleId BIGINT NOT NULL,
    status INT NOT NULL DEFAULT 1,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_department FOREIGN KEY (deptId) REFERENCES department (id),
    CONSTRAINT fk_user_role FOREIGN KEY (roleId) REFERENCES role (id)
);

CREATE TABLE faceFeature (
    id BIGINT PRIMARY KEY,
    userId BIGINT NOT NULL,
    featureData CLOB NOT NULL,
    featureHash VARCHAR(128) NOT NULL,
    encryptFlag INT NOT NULL DEFAULT 1,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_face_feature_user FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_face_feature_hash ON faceFeature (featureHash);
CREATE INDEX idx_face_feature_user_time ON faceFeature (userId, createTime);

CREATE TABLE attendanceRecord (
    id BIGINT PRIMARY KEY,
    userId BIGINT NOT NULL,
    checkTime TIMESTAMP NOT NULL,
    checkType VARCHAR(20) NOT NULL,
    deviceId VARCHAR(64) NOT NULL,
    deviceInfo VARCHAR(128),
    ipAddr VARCHAR(64),
    location VARCHAR(255),
    longitude DECIMAL(10,6),
    latitude DECIMAL(10,6),
    faceScore DECIMAL(5,2),
    status VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_user FOREIGN KEY (userId) REFERENCES user (id),
    CONSTRAINT fk_attendance_device FOREIGN KEY (deviceId) REFERENCES device (id)
);

CREATE TABLE attendanceRepair (
    id BIGINT PRIMARY KEY,
    userId BIGINT NOT NULL,
    checkType VARCHAR(20) NOT NULL,
    checkTime TIMESTAMP NOT NULL,
    repairReason VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    recordId BIGINT,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_repair_user FOREIGN KEY (userId) REFERENCES user (id),
    CONSTRAINT fk_attendance_repair_record FOREIGN KEY (recordId) REFERENCES attendanceRecord (id)
);

CREATE TABLE rule (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    startTime TIME NOT NULL,
    endTime TIME NOT NULL,
    lateThreshold INT NOT NULL DEFAULT 10,
    earlyThreshold INT NOT NULL DEFAULT 10,
    repeatLimit INT NOT NULL DEFAULT 3,
    status INT NOT NULL DEFAULT 1
);

CREATE TABLE attendanceException (
    id BIGINT PRIMARY KEY,
    recordId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    riskLevel VARCHAR(20) NOT NULL,
    sourceType VARCHAR(20) NOT NULL DEFAULT 'RULE',
    description VARCHAR(255),
    processStatus VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_exception_record FOREIGN KEY (recordId) REFERENCES attendanceRecord (id),
    CONSTRAINT fk_attendance_exception_user FOREIGN KEY (userId) REFERENCES user (id)
);

CREATE TABLE promptTemplate (
    id BIGINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sceneType VARCHAR(50) NOT NULL,
    version VARCHAR(50) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR(20) NOT NULL,
    remark VARCHAR(255),
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exceptionAnalysis (
    id BIGINT PRIMARY KEY,
    exceptionId BIGINT NOT NULL,
    promptTemplateId BIGINT,
    inputSummary CLOB,
    modelResult CLOB,
    modelConclusion VARCHAR(100),
    confidenceScore DECIMAL(5,2),
    decisionReason CLOB,
    suggestion VARCHAR(255),
    reasonSummary CLOB,
    actionSuggestion VARCHAR(255),
    similarCaseSummary CLOB,
    promptVersion VARCHAR(50),
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exception_analysis_exception FOREIGN KEY (exceptionId) REFERENCES attendanceException (id)
);

CREATE TABLE reviewRecord (
    id BIGINT PRIMARY KEY,
    exceptionId BIGINT NOT NULL,
    reviewUserId BIGINT NOT NULL,
    result VARCHAR(20) NOT NULL,
    comment VARCHAR(255),
    aiReviewSuggestion CLOB,
    similarCaseSummary CLOB,
    feedbackTag VARCHAR(50),
    strategyFeedback VARCHAR(255),
    reviewTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_record_exception FOREIGN KEY (exceptionId) REFERENCES attendanceException (id),
    CONSTRAINT fk_review_record_user FOREIGN KEY (reviewUserId) REFERENCES user (id)
);

CREATE TABLE exceptionType (
    id BIGINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    status INT NOT NULL,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE riskLevel (
    id BIGINT PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    status INT NOT NULL DEFAULT 1,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE modelCallLog (
    id BIGINT PRIMARY KEY,
    businessType VARCHAR(50) NOT NULL,
    businessId BIGINT NOT NULL,
    promptTemplateId BIGINT,
    inputSummary CLOB,
    outputSummary CLOB,
    status VARCHAR(20) NOT NULL,
    latencyMs INT,
    errorMessage VARCHAR(255),
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE decisionTrace (
    id BIGINT PRIMARY KEY,
    businessType VARCHAR(50) NOT NULL,
    businessId BIGINT NOT NULL,
    ruleResult CLOB,
    modelResult CLOB,
    finalDecision CLOB,
    confidenceScore DECIMAL(5,2),
    decisionReason CLOB,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warningRecord (
    id BIGINT PRIMARY KEY,
    exceptionId BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    level VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNPROCESSED',
    priorityScore DECIMAL(5,2),
    aiSummary CLOB,
    disposeSuggestion VARCHAR(255),
    decisionSource VARCHAR(20),
    sendTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_warning_record_exception FOREIGN KEY (exceptionId) REFERENCES attendanceException (id)
);

CREATE TABLE operationLog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT DEFAULT NULL,
    type VARCHAR(50) NOT NULL,
    content VARCHAR(255) NOT NULL,
    operationTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fkOperationLogUser FOREIGN KEY (userId) REFERENCES user (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uk_role_code ON role (code);
CREATE UNIQUE INDEX uk_user_username ON user (username);
CREATE INDEX idx_attendance_repair_user_time ON attendanceRepair (userId, checkTime);
CREATE UNIQUE INDEX uk_attendance_repair_pending ON attendanceRepair (userId, checkType, checkTime, status);
CREATE UNIQUE INDEX uk_exception_type_code ON exceptionType (code);
CREATE UNIQUE INDEX uk_risk_level_code ON riskLevel (code);
CREATE INDEX idx_review_record_exception_id ON reviewRecord (exceptionId);
CREATE UNIQUE INDEX uk_warning_record_exception ON warningRecord (exceptionId);
CREATE INDEX idxOperationLogUserTime ON operationLog (userId, operationTime);
