CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE role (
    id BIGINT PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    status TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE user (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    realName VARCHAR(50) NOT NULL,
    gender VARCHAR(10),
    phone VARCHAR(20),
    deptId BIGINT NOT NULL,
    roleId BIGINT NOT NULL,
    status INT NOT NULL DEFAULT 1,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_department FOREIGN KEY (deptId) REFERENCES department (id),
    CONSTRAINT fk_user_role FOREIGN KEY (roleId) REFERENCES role (id)
);

CREATE UNIQUE INDEX uk_role_code ON role (code);
CREATE UNIQUE INDEX uk_user_username ON user (username);
